# 80 Puntos

In [1]:
import numpy as np 
import pandas as pd
import math
import random

In [9]:
cities = 10
maxiter = 100
dic={"1":[float('inf') ,49,30,53,72,19,76,87,45,48],"2":[0,float('inf') ,19,38,32,31,75,69,61,25],"3":[0,0,float('inf') ,41,98,56,6,6,45,53],"4":[0,0,0,float('inf') ,52,29,46,90,23,98],
     "5":[0,0,0,0,float('inf') ,63,90,69,50,82],"6":[0,0,0,0,0,float('inf') ,60,88,41,95],"7":[0,0,0,0,0,0,float('inf') ,61,92,10],"8":[0,0,0,0,0,0,0,float('inf') ,82,73],"9":[0,0,0,0,0,0,0,0,float('inf') ,5],
     "10":[0,0,0,0,0,0,0,0,0,float('inf')]}
     

In [10]:
dic

{'1': [inf, 49, 30, 53, 72, 19, 76, 87, 45, 48],
 '2': [0, inf, 19, 38, 32, 31, 75, 69, 61, 25],
 '3': [0, 0, inf, 41, 98, 56, 6, 6, 45, 53],
 '4': [0, 0, 0, inf, 52, 29, 46, 90, 23, 98],
 '5': [0, 0, 0, 0, inf, 63, 90, 69, 50, 82],
 '6': [0, 0, 0, 0, 0, inf, 60, 88, 41, 95],
 '7': [0, 0, 0, 0, 0, 0, inf, 61, 92, 10],
 '8': [0, 0, 0, 0, 0, 0, 0, inf, 82, 73],
 '9': [0, 0, 0, 0, 0, 0, 0, 0, inf, 5],
 '10': [0, 0, 0, 0, 0, 0, 0, 0, 0, inf]}

In [11]:
al = pd.DataFrame.from_dict(dic,orient='index')

al

0     1     2     3     4     5     6     7     8     9
1   inf  49.0  30.0  53.0  72.0  19.0  76.0  87.0  45.0  48.0
2   0.0   inf  19.0  38.0  32.0  31.0  75.0  69.0  61.0  25.0
3   0.0   0.0   inf  41.0  98.0  56.0   6.0   6.0  45.0  53.0
4   0.0   0.0   0.0   inf  52.0  29.0  46.0  90.0  23.0  98.0
5   0.0   0.0   0.0   0.0   inf  63.0  90.0  69.0  50.0  82.0
6   0.0   0.0   0.0   0.0   0.0   inf  60.0  88.0  41.0  95.0
7   0.0   0.0   0.0   0.0   0.0   0.0   inf  61.0  92.0  10.0
8   0.0   0.0   0.0   0.0   0.0   0.0   0.0   inf  82.0  73.0
9   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   inf   5.0
10  0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   inf

In [12]:
count=0
for i in al:
    if al.iloc[i,0] == 0:
        al.iloc[i,0] = al.iloc[0,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,1] == 0:
        al.iloc[i,1] = al.iloc[1,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,2] == 0:
        al.iloc[i,2] = al.iloc[2,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,3] == 0:
        al.iloc[i,3] = al.iloc[3,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,4] == 0:
        al.iloc[i,4] = al.iloc[4,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,5] == 0:
        al.iloc[i,5] = al.iloc[5,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,6] == 0:
        al.iloc[i,6] = al.iloc[6,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,7] == 0:
        al.iloc[i,7] = al.iloc[7,count] 
    count+=1
count=0
for i in al:
    if al.iloc[i,8] == 0:
        al.iloc[i,8] = al.iloc[8,count] 
    count+=1

In [13]:
al

0     1     2     3     4     5     6     7     8     9
1    inf  49.0  30.0  53.0  72.0  19.0  76.0  87.0  45.0  48.0
2   49.0   inf  19.0  38.0  32.0  31.0  75.0  69.0  61.0  25.0
3   30.0  19.0   inf  41.0  98.0  56.0   6.0   6.0  45.0  53.0
4   53.0  38.0  41.0   inf  52.0  29.0  46.0  90.0  23.0  98.0
5   72.0  32.0  98.0  52.0   inf  63.0  90.0  69.0  50.0  82.0
6   19.0  31.0  56.0  29.0  63.0   inf  60.0  88.0  41.0  95.0
7   76.0  75.0   6.0  46.0  90.0  60.0   inf  61.0  92.0  10.0
8   87.0  69.0   6.0  90.0  69.0  88.0  61.0   inf  82.0  73.0
9   45.0  61.0  45.0  23.0  50.0  41.0  92.0  82.0   inf   5.0
10  48.0  25.0  53.0  98.0  82.0  95.0  10.0  73.0   5.0   inf

In [14]:
newa = al.copy()
newa

0     1     2     3     4     5     6     7     8     9
1    inf  49.0  30.0  53.0  72.0  19.0  76.0  87.0  45.0  48.0
2   49.0   inf  19.0  38.0  32.0  31.0  75.0  69.0  61.0  25.0
3   30.0  19.0   inf  41.0  98.0  56.0   6.0   6.0  45.0  53.0
4   53.0  38.0  41.0   inf  52.0  29.0  46.0  90.0  23.0  98.0
5   72.0  32.0  98.0  52.0   inf  63.0  90.0  69.0  50.0  82.0
6   19.0  31.0  56.0  29.0  63.0   inf  60.0  88.0  41.0  95.0
7   76.0  75.0   6.0  46.0  90.0  60.0   inf  61.0  92.0  10.0
8   87.0  69.0   6.0  90.0  69.0  88.0  61.0   inf  82.0  73.0
9   45.0  61.0  45.0  23.0  50.0  41.0  92.0  82.0   inf   5.0
10  48.0  25.0  53.0  98.0  82.0  95.0  10.0  73.0   5.0   inf

In [15]:
new_dict = al.to_numpy().copy()
new_dict

array([[inf, 49., 30., 53., 72., 19., 76., 87., 45., 48.],
       [49., inf, 19., 38., 32., 31., 75., 69., 61., 25.],
       [30., 19., inf, 41., 98., 56.,  6.,  6., 45., 53.],
       [53., 38., 41., inf, 52., 29., 46., 90., 23., 98.],
       [72., 32., 98., 52., inf, 63., 90., 69., 50., 82.],
       [19., 31., 56., 29., 63., inf, 60., 88., 41., 95.],
       [76., 75.,  6., 46., 90., 60., inf, 61., 92., 10.],
       [87., 69.,  6., 90., 69., 88., 61., inf, 82., 73.],
       [45., 61., 45., 23., 50., 41., 92., 82., inf,  5.],
       [48., 25., 53., 98., 82., 95., 10., 73.,  5., inf]])

In [16]:
def powa(new_dict,target):
    for i in range(10):
        new_dict[i][target]  = float('inf')
    

# Initial Solution

In [17]:
def initialsolution(new_dict,dic):
    back = new_dict.copy()
    path= [0]
    total = 0
    currcity = 0
    powa(new_dict,0)
    for i in range(0,9):

        min_= np.argmin(new_dict[currcity])
        total = total + new_dict[currcity][min_]
        path.append(min_)
        currcity = min_
        powa(new_dict,min_)

    path.append(0)
    total = total+dic["1"][path[-2]]
    new_dict = back.copy()

    return path


In [18]:
path_=initialsolution(new_dict,dic)
print(path_)


[0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0]


In [19]:
new_dict

array([[inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf, inf, inf, inf, inf, inf]])

In [20]:
new_dict = al.to_numpy().copy()
new_dict

array([[inf, 49., 30., 53., 72., 19., 76., 87., 45., 48.],
       [49., inf, 19., 38., 32., 31., 75., 69., 61., 25.],
       [30., 19., inf, 41., 98., 56.,  6.,  6., 45., 53.],
       [53., 38., 41., inf, 52., 29., 46., 90., 23., 98.],
       [72., 32., 98., 52., inf, 63., 90., 69., 50., 82.],
       [19., 31., 56., 29., 63., inf, 60., 88., 41., 95.],
       [76., 75.,  6., 46., 90., 60., inf, 61., 92., 10.],
       [87., 69.,  6., 90., 69., 88., 61., inf, 82., 73.],
       [45., 61., 45., 23., 50., 41., 92., 82., inf,  5.],
       [48., 25., 53., 98., 82., 95., 10., 73.,  5., inf]])

# 

# Objective Function

In [21]:
def gettotal(x,new_dict):
    back = new_dict
    total = 0
    currcity = 0
    co = 0
    for i in x:
        if co == 9:
            break
        total = total + new_dict[i][x[co+1]]
        co+=1
    lastcity = x[-2]
    destiny = x[-1]
    total += new_dict[lastcity][destiny]
    new_dict = back

    return total

In [22]:
gettotal([0, 5, 3, 2, 9, 6, 8, 7, 1, 4,0],new_dict)

499.0

# Restriccion

In [23]:
tabu_list = {}

# Movimientos

In [24]:
def getneighborhood(initial):
#initial = [0, 4, 3, 7, 5, 2, 6, 8, 1, 0]
    random_pos = random.randint(1,8)
    rand_num = initial[random_pos]
    newmoves = []
    initial2 = initial.copy()
    bloc = initial.copy()
    #tabu_list[initial[movto]] = time
    for i in range(1,len(initial)-1):
        a = initial[random_pos]
        b = initial[i]
        initial2[random_pos] = b
        initial2[i] = a
        newmoves.append(initial2)
        initial2 = initial.copy()
    
    newmoves.remove(bloc) 
    return newmoves,rand_num

In [25]:
tabu_list

{}

In [26]:
getneighborhood([0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0])


([[0, 1, 3, 8, 9, 6, 2, 7, 5, 4, 0],
  [0, 5, 1, 8, 9, 6, 2, 7, 3, 4, 0],
  [0, 5, 3, 1, 9, 6, 2, 7, 8, 4, 0],
  [0, 5, 3, 8, 1, 6, 2, 7, 9, 4, 0],
  [0, 5, 3, 8, 9, 1, 2, 7, 6, 4, 0],
  [0, 5, 3, 8, 9, 6, 1, 7, 2, 4, 0],
  [0, 5, 3, 8, 9, 6, 2, 1, 7, 4, 0],
  [0, 5, 3, 8, 9, 6, 2, 7, 4, 1, 0]],
 1)

In [27]:
new_dict

array([[inf, 49., 30., 53., 72., 19., 76., 87., 45., 48.],
       [49., inf, 19., 38., 32., 31., 75., 69., 61., 25.],
       [30., 19., inf, 41., 98., 56.,  6.,  6., 45., 53.],
       [53., 38., 41., inf, 52., 29., 46., 90., 23., 98.],
       [72., 32., 98., 52., inf, 63., 90., 69., 50., 82.],
       [19., 31., 56., 29., 63., inf, 60., 88., 41., 95.],
       [76., 75.,  6., 46., 90., 60., inf, 61., 92., 10.],
       [87., 69.,  6., 90., 69., 88., 61., inf, 82., 73.],
       [45., 61., 45., 23., 50., 41., 92., 82., inf,  5.],
       [48., 25., 53., 98., 82., 95., 10., 73.,  5., inf]])

In [28]:
new_dict = al.to_numpy().copy()
new_dict

array([[inf, 49., 30., 53., 72., 19., 76., 87., 45., 48.],
       [49., inf, 19., 38., 32., 31., 75., 69., 61., 25.],
       [30., 19., inf, 41., 98., 56.,  6.,  6., 45., 53.],
       [53., 38., 41., inf, 52., 29., 46., 90., 23., 98.],
       [72., 32., 98., 52., inf, 63., 90., 69., 50., 82.],
       [19., 31., 56., 29., 63., inf, 60., 88., 41., 95.],
       [76., 75.,  6., 46., 90., 60., inf, 61., 92., 10.],
       [87., 69.,  6., 90., 69., 88., 61., inf, 82., 73.],
       [45., 61., 45., 23., 50., 41., 92., 82., inf,  5.],
       [48., 25., 53., 98., 82., 95., 10., 73.,  5., inf]])

# Tabu List

In [29]:
tabu_list = {}
tabu_list[0] = [initialsolution(new_dict,dic),cities/2]
print(tabu_list)

{0: [[0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0], 5.0]}


In [30]:
tabu_list

{0: [[0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0], 5.0]}

In [31]:
def updateTabuList(new_element,indez, tabu_list,time):

    aux = []
#a_dict[key]
    for key in tabu_list:
        tabu_list[key] -= 1
        if tabu_list[key] == 0:
            aux.append(key)
    for key in aux:
        tabu_list.pop(key)
    #tabu_list[list(tabu_list)[-1]+1] = [new_element,time]
    tabu_list[indez] = time

In [32]:
updateTabuList([0, 8, 3, 5, 9, 6, 2, 7, 1, 4, 0],6,tabu_list,5)

TypeError: unsupported operand type(s) for -=: 'list' and 'int'

In [33]:
tabu_list

{0: [[0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0], 5.0]}

In [34]:
asdasd = [0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0]
contains_1 = 1 in a_dictionary.values()

for i in range(len(tabu_list)):
    print(tabu_list[i])

NameError: name 'a_dictionary' is not defined

In [35]:
new_dict = al.to_numpy().copy()
new_dict

array([[inf, 49., 30., 53., 72., 19., 76., 87., 45., 48.],
       [49., inf, 19., 38., 32., 31., 75., 69., 61., 25.],
       [30., 19., inf, 41., 98., 56.,  6.,  6., 45., 53.],
       [53., 38., 41., inf, 52., 29., 46., 90., 23., 98.],
       [72., 32., 98., 52., inf, 63., 90., 69., 50., 82.],
       [19., 31., 56., 29., 63., inf, 60., 88., 41., 95.],
       [76., 75.,  6., 46., 90., 60., inf, 61., 92., 10.],
       [87., 69.,  6., 90., 69., 88., 61., inf, 82., 73.],
       [45., 61., 45., 23., 50., 41., 92., 82., inf,  5.],
       [48., 25., 53., 98., 82., 95., 10., 73.,  5., inf]])

In [36]:
def getbestneighborhood(neigh,new_dict):
    #neigh = getneighborhood(neighbor)
    indextotal= []
    for i in range(0,len(neigh)):
        curr = gettotal(neigh[i],new_dict)
        indextotal.append(curr)
    while True:
        minindex = np.argmin(indextotal)
        if neigh[minindex] in tabu_list.values():
            neigh.pop(minindex)
            indextotal.pop(minindex)
        else:
            return neigh[minindex]
            break
        
        


In [37]:
tabu_list={}

In [38]:
len(tabu_list)

0

In [39]:
def reductedneighborhood(initial,new_dict,tabu_list):
    #initial = [0, 4, 3, 7, 5, 2, 6, 8, 1, 0]
    random_pos = random.randint(1,8)
    rand_num = initial[random_pos]
    newmoves = []
    initial2 = initial.copy()
    bloc = initial.copy()
    #tabu_list[initial[movto]] = time
    for i in range(1,len(initial)-1):
        a = initial[random_pos]
        b = initial[i]
        initial2[random_pos] = b
        initial2[i] = a
        newmoves.append(initial2)
        initial2 = initial.copy()
    newmoves.remove(bloc)
    if len(tabu_list) == 0:
        tabu_list[rand_num] = 5
    indextotal= []
    for i in range(0,len(newmoves)):
        curr = gettotal(newmoves[i],new_dict)
        indextotal.append(curr)
    while True:
        minindex = np.argmin(indextotal)
        if newmoves[minindex] in tabu_list.values():
            newmoves.pop(minindex)
            indextotal.pop(minindex)
        else:
            return newmoves[minindex],rand_num
            
      

In [40]:
reductedneighborhood([0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0],new_dict,tabu_list)


([0, 4, 3, 8, 9, 6, 2, 7, 1, 5, 0], 5)

In [41]:
tabu_list

{5: 5}

In [42]:
def getneighborhood(initial):
#initial = [0, 4, 3, 7, 5, 2, 6, 8, 1, 0]
    random_pos = random.randint(1,8)
    rand_num = initial[random_pos]
    newmoves = []
    initial2 = initial.copy()
    bloc = initial.copy()
    #tabu_list[initial[movto]] = time
    for i in range(1,len(initial)-1):
        a = initial[random_pos]
        b = initial[i]
        initial2[movto] = b
        initial2[i] = a
        newmoves.append(initial2)
        initial2 = initial.copy()
    
    newmoves.remove(bloc) 
    return newmoves,rand_num

In [43]:
neigh

NameError: name 'neigh' is not defined

In [44]:
neigh.pop(5)

NameError: name 'neigh' is not defined

In [45]:
new_dict = al.to_numpy().copy()
new_dict

array([[inf, 49., 30., 53., 72., 19., 76., 87., 45., 48.],
       [49., inf, 19., 38., 32., 31., 75., 69., 61., 25.],
       [30., 19., inf, 41., 98., 56.,  6.,  6., 45., 53.],
       [53., 38., 41., inf, 52., 29., 46., 90., 23., 98.],
       [72., 32., 98., 52., inf, 63., 90., 69., 50., 82.],
       [19., 31., 56., 29., 63., inf, 60., 88., 41., 95.],
       [76., 75.,  6., 46., 90., 60., inf, 61., 92., 10.],
       [87., 69.,  6., 90., 69., 88., 61., inf, 82., 73.],
       [45., 61., 45., 23., 50., 41., 92., 82., inf,  5.],
       [48., 25., 53., 98., 82., 95., 10., 73.,  5., inf]])

# Todo completo

In [46]:
def TabuSearch(maxiter, cities,new_dict,dic):

    back = new_dict.copy()
    x = initialsolution(new_dict,dic)
    new_dict = back.copy()
    f_x = gettotal(x,new_dict)
    BestX = x.copy()
    BestF = f_x
    tabu_list = {}
    tabu_time = cities//2
    #Definimos el tiempo tabú

    for k in range(maxiter):
        #Obtenemos nuestro vecindario reducido
        #neighborhood = getneighborhood(x)
        #Si nuestro vecindario está vacío, ya no podemos movernos
        #a otra solución y debemos terminar la búsqueda
        #if len(neighborhood) == 0:
        #    break
        #Nuestra siguiente solución es la mejor del vecindario
        best_neighbor = reductedneighborhood(x,new_dict,tabu_list)
        new_dict = back.copy()
        x,inde = best_neighbor
        f_x = gettotal(x,new_dict)
        #Verificamos si la nueva solución
        #es mejor que lo que conocemos
        if f_x <= BestF:
            BestX = x.copy()
            BestF = f_x
        #Actualizamos la lista tabú
        updateTabuList(x,inde, tabu_list,tabu_time)
    new_dict = back.copy()

    return BestX, BestF


In [63]:
TabuSearch(maxiter,cities,new_dict.copy(),dic)

([0, 5, 1, 4, 3, 8, 9, 6, 7, 2, 0], 269.0)

# 20 Puntos

## Input

In [4]:
def tabucustom():
    print("Txt name")
    txt = input()
    print("M iterations")
    M = int(input())
        
    with open(txt, 'r') as file:
         input_lines = [line.strip() for line in file]
    global cities 
    cities = int(input_lines[0])
    maxiter = int(input_lines[1])




    cost_city = [] 
    for i in range(2,cities+1):
        costos_ni = list(map(int,input_lines[i].split()))
        cost_city.append(costos_ni)

    new_cost = np.zeros((cities, cities))
    for i in range(len(cost_city)+1):
        new_cost[i][i] = float('inf')
    c = 1
    for i in range(len(cost_city)):
        new_cost[i][c:] = cost_city[i]
        c+=1
    dic = {idx + 1 : new_cost[idx] for idx in range(len(new_cost))} 
    #######################################################
    for j in range(cities):
        count=0
        for i in range(len(new_cost[j])):#sera j
            if new_cost[i][j] == 0:
                new_cost[i][j] =new_cost[j][count]
            count+=1
           
            
    def powa(new_dict,target):
        
        global cities
        for i in range(cities):
            new_dict[i][target]  = float('inf')

    def initialsolution(new_dict,dic):
        global cities
        back = new_dict.copy()
        path= [0]
        total = 0
        currcity = 0
        powa(new_dict,0)
        for i in range(0,cities-1):

            min_= np.argmin(new_dict[currcity])
            total = total + new_dict[currcity][min_]
            path.append(min_)
            currcity = min_
            powa(new_dict,min_)

        path.append(0)
        total = total+dic[1][path[-2]]
        new_dict = back.copy()

        return path
    

    
    def gettotal(x,new_dict):
        back = new_dict
        total = 0
        currcity = 0
        co = 0
        for i in x:
            if co == 9:
                break
            total = total + new_dict[i][x[co+1]]
            co+=1
        lastcity = x[-2]
        destiny = x[-1]
        total += new_dict[lastcity][destiny]
        new_dict = back

        return total


    def getneighborhood(initial):
        global cities
        random_pos = random.randint(1,cities-2)
        rand_num = initial[random_pos]
        newmoves = []
        initial2 = initial.copy()
        bloc = initial.copy()
        #tabu_list[initial[movto]] = time
        for i in range(1,len(initial)-1):
            a = initial[random_pos]
            b = initial[i]
            initial2[random_pos] = b
            initial2[i] = a
            newmoves.append(initial2)
            initial2 = initial.copy()

        newmoves.remove(bloc) 
        return newmoves,rand_num


    def updateTabuList(new_element,indez, tabu_list,time):
        aux = []
        for key in tabu_list:
            tabu_list[key] -= 1
            if tabu_list[key] == 0:
                aux.append(key)
        for key in aux:
            tabu_list.pop(key)
        tabu_list[indez] = time

    def reductedneighborhood(initial,new_dict,tabu_list):
        global cities
        random_pos = random.randint(1,cities-2)
        rand_num = initial[random_pos]
        newmoves = []
        initial2 = initial.copy()
        bloc = initial.copy()
        for i in range(1,len(initial)-1):
            a = initial[random_pos]
            b = initial[i]
            initial2[random_pos] = b
            initial2[i] = a
            newmoves.append(initial2)
            initial2 = initial.copy()
        newmoves.remove(bloc)
        if len(tabu_list) == 0:
            tabu_list[rand_num] = 5
        indextotal= []
        for i in range(0,len(newmoves)):
            curr = gettotal(newmoves[i],new_dict)
            indextotal.append(curr)
        while True:
            minindex = np.argmin(indextotal)
            if newmoves[minindex] in tabu_list.values():
                newmoves.pop(minindex)
                indextotal.pop(minindex)
            else:
                return newmoves[minindex],rand_num


    def TabuSearch(maxiter, cities,new_dict,dic):

        back = new_dict.copy()
        x = initialsolution(new_dict,dic)
        new_dict = back.copy()
        f_x = gettotal(x,new_dict)
        BestX = x.copy()
        BestF = f_x
        tabu_list = {}
        tabu_time = cities//2
        #Definimos el tiempo tabú

        for k in range(maxiter):

            best_neighbor = reductedneighborhood(x,new_dict,tabu_list)
            new_dict = back.copy()
            x,inde = best_neighbor
            f_x = gettotal(x,new_dict)
            if f_x <= BestF:
                BestX = x.copy()
                BestF = f_x
            updateTabuList(x,inde, tabu_list,tabu_time)
        new_dict = back.copy()

        return BestX, BestF

    solutions =[]
    best = float('inf')
    best_index = 0
    worst = 0
    worst_index = 0
    for i in range(M):
        curr = TabuSearch(maxiter,cities,new_cost.copy(),dic)
        if curr[1] < best:
            best = curr[1]
            best_index = curr[0]
        if curr[1] > worst:
            worst = curr[1]
            worst_index = curr[0]

        solutions.append(curr)



    def get_median(n):
        n = sorted(solutions, key=lambda tup: tup[1])
        l = len(n)
        if l%2 == 0:
            return n[(l//2)]
        else:
            return n[(l//2)-1]

    def mean(solutions):
        mean = 0
        for i in range(len(solutions)):
            mean = mean +solutions[i][1]
        return (mean/len(solutions))

    def std(solutions):
        m = mean(solutions)
        all_ = 0
        for i in range(len(solutions)):
            all_ = all_ + (solutions[i][1] - m)**2
        return np.sqrt(all_/len(solutions))
    print("Best Solution:",best_index,best)
    print("Worst Solution:",worst_index,worst)
    print("Median:",get_median(solutions))
    print("Mean: ",mean(solutions))
    print("Standard deviation:",std(solutions))

In [5]:
tabucustom()

Txt name


 untitled.txt


M iterations


 100


Best Solution: [0, 5, 1, 4, 3, 8, 9, 6, 2, 7, 11, 10, 0] 239.0
Worst Solution: [0, 5, 3, 8, 9, 6, 2, 7, 10, 1, 4, 11, 0] 274.0
Median: ([0, 5, 3, 8, 9, 6, 2, 1, 4, 10, 7, 11, 0], 264.0)
Mean:  262.78
Standard deviation: 8.810879638265408


In [6]:
tabucustom()

Txt name


 Real.txt


M iterations


 200


Best Solution: [0, 5, 3, 8, 9, 6, 2, 7, 4, 1, 0] 248.0
Worst Solution: [0, 5, 3, 8, 9, 6, 2, 7, 1, 4, 0] 271.0
Median: ([0, 5, 3, 1, 4, 7, 2, 6, 9, 8, 0], 259.0)
Mean:  259.845
Standard deviation: 10.333488036476357
